export const ROOM_LIST_REQUESTE = "ROOM_LIST_REQUESTE";
export const ROOM_LIST_SUCCESS = "ROOM_LIST_SUCCESS";
export const ROOM_LIST_FAIL = "ROOM_LIST_FAIL";

export const ROOM_DETAILS_REQUESTE = "ROOM_DETAILS_REQUESTE";
export const ROOM_DETAILS_SUCCESS = "ROOM_DETAILS_SUCCESS";
export const ROOM_DETAILS_FAIL = "ROOM_DETAILS_FAIL";
