export const ROOM_LIST_REQUESTE = "ROOM_LIST_REQUESTE";
export const ROOM_LIST_SUCCESS = "ROOM_LIST_SUCCESS";
export const ROOM_LIST_FAIL = "ROOM_LIST_FAIL";

export const ROOM_DETAILS_REQUESTE = "ROOM_DETAILS_REQUESTE";
export const ROOM_DETAILS_SUCCESS = "ROOM_DETAILS_SUCCESS";
export const ROOM_DETAILS_FAIL = "ROOM_DETAILS_FAIL";

export const ROOM_CREATE_REQUESTE = "ROOM_CREATE_REQUESTE";
export const ROOM_CREATE_SUCCESS = "ROOM_CREATE_SUCCESS";
export const ROOM_CREATE_FAIL = "ROOM_CREATE_FAIL";
export const ROOM_CREATE_RESET = "ROOM_CREATE_RESET";

export const ROOM_DELETE_REQUESTE = "ROOM_DELETE_REQUESTE";
export const ROOM_DELETE_SUCCESS = "ROOM_DELETE_SUCCESS";
export const ROOM_DELETE_FAIL = "ROOM_DELETE_FAIL";

export const ROOM_UPDATE_REQUESTE = "ROOM_UPDATE_REQUESTE";
export const ROOM_UPDATE_SUCCESS = "ROOM_UPDATE_SUCCESS";
export const ROOM_UPDATE_FAIL = "ROOM_UPDATE_FAIL";
export const ROOM_UPDATE_RESET = "ROOM_UPDATE_RESET";

export const USER_ROOM_REQUESTE = "USER_ROOM_REQUESTE";
export const USER_ROOM_SUCCESS = "USER_ROOM_SUCCESS";
export const USER_ROOM_FAIL = "USER_ROOM_FAIL";
