const rooms = [
  {
    id: 1,
    owner: "sanjay rishidev",
    title: "2 room with 1 kitchen",
    address: "kharibot ktm",
    city: "kathmandu",
    description:
      "2 bedroom with 1 kitchen and 1 bathroom located in kharibot kumarigal kathmandu",
    price: 10000,
    bedroom: 2,
    bathroom: 1,
    sqft: 1200,
    garage: "Yes",
    photomain: "https://avatars.githubusercontent.com/u/1?v=4",
    images: ["/images/room1.jpg", "/images/room2.jpg", "/images/room3.jpg"],
    start: "2021-2-13",
  },
  {
    id: 2,
    owner: "bibek raj tripathi",
    title: "1 room with 1 kitchen",
    address: "chabhail",
    city: "kathmandu",
    description:
      "1 bedroom with 1 kitchen and 1 bathroom located in  kathmandu",
    price: 9000,
    bedroom: 1,
    bathroom: 1,
    sqft: 1980,
    garage: "Yes",
    photomain: "/images/room1.jpg",
    images: [
      "/images/room3.jpg",
      "/images/room1.jpg",
      "/images/room2.jpg",
      "/images/room4.jpg",
      "/images/room5.jpeg",
      "/images/room6.jpg",
    ],
    start: "2021-2-11",
  },
  {
    id: 3,
    owner: "bibek raj tripathi",
    title: "1 room with 1 kitchen",
    address: "chabhail",
    city: "kathmandu",
    description:
      "1 bedroom with 1 kitchen and 1 bathroom located in  kathmandu",
    price: 9000,
    bedroom: 1,
    bathroom: 1,
    garage: "No",
    photomain: "/images/room2.jpg",
    images: [
      "/images/room3.jpg",
      "/images/room1.jpg",
      "/images/room2.jpg",
      "/images/room4.jpg",
      "/images/room5.jpeg",
      "/images/room6.jpg",
    ],
    start: "2021-2-12",
  },
  {
    id: 4,
    owner: "bibek raj tripathi",
    title: "1 room with 1 kitchen",
    address: "chabhail",
    city: "kathmandu",
    description:
      "1 bedroom with 1 kitchen and 1 bathroom located in  kathmandu",
    price: 8000,
    bedroom: 1,
    bathroom: 1,
    garage: "Yes",
    photomain: "/images/room2.jpg",
    images: [
      "/images/room3.jpg",
      "/images/room1.jpg",
      "/images/room2.jpg",
      "/images/room4.jpg",
      "/images/room5.jpeg",
      "/images/room6.jpg",
    ],
    start: "2021-2-13",
  },
  {
    id: 5,
    owner: "bibek raj tripathi",
    title: "1 room with 1 kitchen",
    address: "chabhail",
    city: "kathmandu",
    description:
      "1 bedroom with 1 kitchen and 1 bathroom located in  kathmandu",
    price: 5000,
    bedroom: 1,
    bathroom: 1,
    sqft: 8800,
    garage: "Yes",
    photomain: "/images/room2.jpg",
    images: [
      "/images/room3.jpg",
      "/images/room1.jpg",
      "/images/room2.jpg",
      "/images/room4.jpg",
      "/images/room5.jpeg",
      "/images/room6.jpg",
    ],
    start: "2021-2-14",
  },
  {
    id: 16,
    owner: "Amit Awal",
    title: "1 room",
    address: "suryabinyak",
    city: "bhaktaput",
    description: "1 room near suryabinayk chok",
    price: 3000,
    bedroom: 1,
    bathroom: 1,
    sqft: 800,
    garage: "Yes",
    photomain: "/images/room3.jpg",
    images: ["/images/room3.jpg", "/images/room1.jpg"],
    start: "2021-2-01",
  },
  {
    id: 6,
    owner: "bibek raj tripathi",
    title: "1 room with 1 kitchen",
    address: "chabhail",
    city: "kathmandu",
    description:
      "1 bedroom with 1 kitchen and 1 bathroom located in  kathmandu",
    price: 5000,
    bedroom: 1,
    bathroom: 1,
    sqft: 8800,
    garage: "Yes",
    photomain: "/images/room2.jpg",
    images: [
      "/images/room3.jpg",
      "/images/room1.jpg",
      "/images/room2.jpg",
      "/images/room4.jpg",
      "/images/room5.jpeg",
      "/images/room6.jpg",
    ],
    start: "2021-2-14",
  },
  {
    id: 7,
    owner: "bibek raj tripathi",
    title: "1 room with 1 kitchen",
    address: "chabhail",
    city: "kathmandu",
    description:
      "1 bedroom with 1 kitchen and 1 bathroom located in  kathmandu",
    price: 5000,
    bedroom: 1,
    bathroom: 1,
    sqft: 8800,
    garage: "Yes",
    photomain: "/images/room2.jpg",
    images: [
      "/images/room3.jpg",
      "/images/room1.jpg",
      "/images/room2.jpg",
      "/images/room4.jpg",
      "/images/room5.jpeg",
      "/images/room6.jpg",
    ],
    start: "2021-2-14",
  },
  {
    id: 8,
    owner: "bibek raj tripathi",
    title: "1 room with 1 kitchen",
    address: "chabhail",
    city: "kathmandu",
    description:
      "1 bedroom with 1 kitchen and 1 bathroom located in  kathmandu",
    price: 5000,
    bedroom: 1,
    bathroom: 1,
    sqft: 8800,
    garage: "Yes",
    photomain: "/images/room2.jpg",
    images: [
      "/images/room3.jpg",
      "/images/room1.jpg",
      "/images/room2.jpg",
      "/images/room4.jpg",
      "/images/room5.jpeg",
      "/images/room6.jpg",
    ],
    start: "2021-2-14",
  },
  {
    id: 9,
    owner: "bibek raj tripathi",
    title: "1 room with 1 kitchen",
    address: "chabhail",
    city: "kathmandu",
    description:
      "1 bedroom with 1 kitchen and 1 bathroom located in  kathmandu",
    price: 5000,
    bedroom: 1,
    bathroom: 1,
    sqft: 8800,
    garage: "Yes",
    photomain: "/images/room2.jpg",
    images: [
      "/images/room3.jpg",
      "/images/room1.jpg",
      "/images/room2.jpg",
      "/images/room4.jpg",
      "/images/room5.jpeg",
      "/images/room6.jpg",
    ],
    start: "2021-2-14",
  },
  {
    id: 10,
    owner: "bibek raj tripathi",
    title: "1 room with 1 kitchen",
    address: "chabhail",
    city: "kathmandu",
    description:
      "1 bedroom with 1 kitchen and 1 bathroom located in  kathmandu",
    price: 5000,
    bedroom: 1,
    bathroom: 1,
    sqft: 8800,
    garage: "Yes",
    photomain: "/images/room2.jpg",
    images: [
      "/images/room3.jpg",
      "/images/room1.jpg",
      "/images/room2.jpg",
      "/images/room4.jpg",
      "/images/room5.jpeg",
      "/images/room6.jpg",
    ],
    start: "2021-2-14",
  },
  {
    id: 11,
    owner: "bibek raj tripathi",
    title: "1 room with 1 kitchen",
    address: "chabhail",
    city: "kathmandu",
    description:
      "1 bedroom with 1 kitchen and 1 bathroom located in  kathmandu",
    price: 5000,
    bedroom: 1,
    bathroom: 1,
    sqft: 8800,
    garage: "Yes",
    photomain: "/images/room2.jpg",
    images: [
      "/images/room3.jpg",
      "/images/room1.jpg",
      "/images/room2.jpg",
      "/images/room4.jpg",
      "/images/room5.jpeg",
      "/images/room6.jpg",
    ],
    start: "2021-2-14",
  },
  {
    id: 12,
    owner: "bibek raj tripathi",
    title: "1 room with 1 kitchen",
    address: "chabhail",
    city: "kathmandu",
    description:
      "1 bedroom with 1 kitchen and 1 bathroom located in  kathmandu",
    price: 5000,
    bedroom: 1,
    bathroom: 1,
    sqft: 8800,
    garage: "Yes",
    photomain: "/images/room2.jpg",
    images: [
      "/images/room3.jpg",
      "/images/room1.jpg",
      "/images/room2.jpg",
      "/images/room4.jpg",
      "/images/room5.jpeg",
      "/images/room6.jpg",
    ],
    start: "2021-2-14",
  },
  {
    id: 13,
    owner: "bibek raj tripathi",
    title: "1 room with 1 kitchen",
    address: "chabhail",
    city: "kathmandu",
    description:
      "1 bedroom with 1 kitchen and 1 bathroom located in  kathmandu",
    price: 5000,
    bedroom: 1,
    bathroom: 1,
    sqft: 8800,
    garage: "Yes",
    photomain: "/images/room2.jpg",
    images: [
      "/images/room3.jpg",
      "/images/room1.jpg",
      "/images/room2.jpg",
      "/images/room4.jpg",
      "/images/room5.jpeg",
      "/images/room6.jpg",
    ],
    start: "2021-2-14",
  },
  {
    id: 14,
    owner: "bibek raj tripathi",
    title: "1 room with 1 kitchen",
    address: "chabhail",
    city: "kathmandu",
    description:
      "1 bedroom with 1 kitchen and 1 bathroom located in  kathmandu",
    price: 5000,
    bedroom: 1,
    bathroom: 1,
    sqft: 8800,
    garage: "Yes",
    photomain: "/images/room2.jpg",
    images: [
      "/images/room3.jpg",
      "/images/room1.jpg",
      "/images/room2.jpg",
      "/images/room4.jpg",
      "/images/room5.jpeg",
      "/images/room6.jpg",
    ],
    start: "2021-2-14",
  },
  {
    id: 15,
    owner: "bibek raj tripathi",
    title: "1 room with 1 kitchen",
    address: "chabhail",
    city: "kathmandu",
    description:
      "1 bedroom with 1 kitchen and 1 bathroom located in  kathmandu",
    price: 5000,
    bedroom: 1,
    bathroom: 1,
    sqft: 8800,
    garage: "Yes",
    photomain: "/images/room2.jpg",
    images: [
      "/images/room3.jpg",
      "/images/room1.jpg",
      "/images/room2.jpg",
      "/images/room4.jpg",
      "/images/room5.jpeg",
      "/images/room6.jpg",
    ],
    start: "2021-2-14",
  },
];

export default rooms;
